title: Hyunwoo's Dev Blog
description: 

url: https://hyunwoo9930.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large
timezone: Asia/Seoul

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

collections:
  projects:
    output: true
    permalink: /project/:name/

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Project
      url: /project
    - title: Article
      url: /article

social:
    github: hyunwoo9930
    email: hw62459930@gmail.com
    youtube: RickAstleyYT
    tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr